[package]
name = "lead_lang_std"
version = "0.0.0-dev-lead-lang"
edition = "2021"
description = "Standard Package of the Lead Programming Language"
license = "MIT"

[lib]
name = "lead_std"
crate-type = ["cdylib", "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inquire = "0.7.4"
lead_lang_interpreter = { path = "../../interpreter" }
lead_lang_macros = { path = "../../macros" }

[patch.crates-io]
lead_lang_interpreter = { path = "../../interpreter" }
