#! /bin/sh

set -e  # Equivalent to `$ErrorActionPreference = "Stop"`

ERR="\033[31m\033[1m[ERRR]\033[0m"  # Red and bold "[ERRR]"

if [ $# -gt 0 ] && [ "$(printf %s "$1" | cut -c 1)" = "+" ]; then
  data="+stable +nightly +current"
  if echo "$data" | grep -q -- "$1"; then
    channel=$(printf %s "$1" | cut -c 2-)

    path="$LEAD_HOME/versions/$channel"
    if [ ! -e "$path" ]; then
      echo "$ERR The channel $channel is not yet installed. Use \033[32mleadman install\033[0m" >&2
      exit 1
    fi
    ver=$(cat "$path")
  else
    ver=$(printf %s "$1" | tr -d '+')
  fi
else
  channel="current"

  path="$LEAD_HOME/versions/current"
  if [ ! -e "$path" ]; then
    echo "$ERR The channel $channel is not yet installed. Use \033[32mleadman install\033[0m" >&2
    exit 1
  fi
  ver=$(cat "$path")
fi

if [ -z "$ver" ]; then
  echo "$ERR No version has been marked as \033[36m$channel\033[0m. Use \033[32mlead [+stable / +nightly / +version] [args]\033[0m" >&2
  exit 1
fi

lead_path="$LEAD_HOME/versions/$ver/lead"
exec_path="$LEAD_HOME/versions/$ver/leadc"

if [ ! -e "$lead_path" ]; then
  echo "$ERR Your provided version \033[36m$ver\033[0m is invalid or not installed. Use \033[32mlead [+stable / +nightly / +version] [args]\033[0m" >&2
  exit 1
fi

if [ ! -e "$exec_path" ]; then
  echo "$ERR The provided version \033[36m$ver\033[0m does not come with leadc. Use a different version" >&2
  exit 1
fi

if [ $# -gt 0 ] && [ "$(printf %s "$1" | cut -c 1)" = "+" ]; then
  if [ $# -gt 1 ]; then
    set -- "${@:2}"
  else
    set --
  fi
fi

if [ $# -eq 0 ]; then
  "$exec_path"
else
  "$exec_path" "$@"
fi
